"""Generate Pydantic models from ant-connect-ts JSON Schema.

Usage: uv run python scripts/generate_models.py
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT.parent / "ant-connect-ts" / "build" / "comms.schema.json"
OUTPUT = ROOT / "src" / "ant_connect_streamlit" / "models.py"

if not SCHEMA.exists():
    print(f"Schema not found: {SCHEMA}", file=sys.stderr)
    print("Run: cd packages/ant-connect-ts && pnpm run generate:schema", file=sys.stderr)
    sys.exit(1)

result = subprocess.run(
    [
        sys.executable, "-m", "datamodel_code_generator",
        "--input", str(SCHEMA),
        "--output", str(OUTPUT),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--snake-case-field",
        "--target-python-version", "3.11",
        "--use-union-operator",
        "--force-optional",
    ],
    capture_output=True,
    text=True,
)

if result.returncode != 0:
    print(f"datamodel-codegen failed:\n{result.stderr}", file=sys.stderr)
    sys.exit(1)

content = OUTPUT.read_text()

content = re.sub(
    r"#\s*generated by datamodel-codegen:.*?\n(?:#.*?\n)*",
    "# AUTO-GENERATED from ant-connect-ts types — do not edit manually.\n"
    "# Regenerate: cd packages/ant-connect-ts && pnpm run generate:python-types\n",
    content,
    count=1,
)

content = content.replace("extra='forbid'", "extra='ignore', populate_by_name=True")

OUTPUT.write_text(content)

print(f"Generated {OUTPUT} ({len(content.splitlines())} lines)")
